log_level: info
server:
  port: 5557
embeddings:
  # Modifying the device to cuda requires a container with CUDA installed
  # and torch with CUDA support
  device: cpu
  messages:
    enabled: true
    model: moka-ai/m3e-base
  documents:
    enabled: true
    model: moka-ai/m3e-base
    # This is the recommended, moderate-memory model for document embeddings
#    model: multi-qa-mpnet-base-dot-v1
nlp:
  spacy_model: /app/.venv/lib/python3.11/site-packages/en_core_web_sm/en_core_web_sm-3.6.0
